Bluntsord/added new instructions
quantum-defence/quantum-defence pull request #123
Opened 2021-07-23 17:08 UTC by Bluntsord

Added some "Scoping" which is basically some spotlight like thing

2021-07-23 17:38 UTC, Bluntsord commented
Still need to relook at text and make forward backward button for prompt

2021-07-24 15:37 UTC, bharathcs requested changes

2021-07-24 15:37 UTC, bharathcs commented on game/src/Scope/TowerButtonScopes.gd
> +	+ "Alternatively you can press Q on your keyboard"
Hmm Q swaps colour tho?

2021-07-24 15:37 UTC, bharathcs commented on game/project.godot
> +"class": "prompt",
Oof could classes start with capital letter please

2021-07-24 15:37 UTC, bharathcs commented on game/src/Scope/GoldScoping.gd
> +var instructions = "This is gold you have\n " \
This is the gold you have:
Killing enemies drop gold and
Building towers cost gold

That's all for now. Have fun!

Missing spaces, capitalisation, and grammar fix.

2021-07-24 15:37 UTC, bharathcs commented on game/src/Scope/HealthBarScopeLabel.gd
> +	+ "If any reaches zero, GAMEOVER"
GAMEOVER -> GAME OVER

2021-07-24 15:37 UTC, bharathcs commented on game/src/Scope/ItemScoping.gd
> +	+ "and equip an item by dragging and dropping"
```
var instructions = "These are the items. Items dropped by enemies\n " \
	+ "can be clicked on and will appear here\n" \
	+ "Open a tower inventory by clicking on a tower\n" \

var instructions = "Click on the items dropped by enemies\n " \
	+ "to have them appear here." .....
```

2021-07-24 15:37 UTC, bharathcs commented on game/src/Scope/QuantumButton.gd
> +	+ "Click here\n to swap between color" \
er minor thing but it should probably be colour since the name of the game is in British English (the c in defence)

2021-07-24 15:37 UTC, bharathcs commented on game/src/environment/Fog/Black.shader
> +uniform vec4 color = vec4(0, 0, 0, 1);
I do believe this variable should be renamed as black

2021-07-24 15:37 UTC, bharathcs commented on game/src/ui/gameplay/Prompts/AnimatedSprite.gd
>  ]
```
"Protect your portals!\n Red enemies go to red portal\nand blue enemies go\nto blue portal. Each tower\ncan only hit enemies \nof the same color",
	"Add quantum items to the towers \nto allow enemies to change \nbetween colors",
	"Hadamard(Orange) gives a \n50/50 chance",
	"RY item(Green) gives a \n12.5/87.5 chance",
	"And the classical X gate(Blue)\n is a 0/100 chance",
	"Enemies that change color\n are forced to walk to\n the new colors portal",
	"This lengthens the time\n u can attack them",
	"Build towers to defend ur portal\n the gold of each \ntower is displayed at the top",
	"This lengthens the time\n you can attack them",
	"Build towers to defend your portal\n the gold of each \ntower is displayed at the top",
	"However BEWARE Quantum towers\n do not do any damage!, they only\n change the color of enemies"
```

Protect your portals!
Red enemies attack through the red portal
and blue enemies attack through the blue portal. Enemy colour is set by the qubit they contain, and each tower only hits enemies of the same colour. 

Add quantum items to the towers to ~~allow enemies to change~~ force an enemy into a colour based on the quantum circuitry in the item. If it flips them into the opposite colour, the enemy is forced to turn around and go to its new target, which lets you rack up more hits along its path. However, BEWARE that these quantum towers do not do any damage, and they only affect the qubit (colour) of the enemy.

Hadamard (Orange) will put the enemy back into equal superposition before the weapon collapses it. A **red** tower equipped with Hadamard will turn on average 50% of the red enemies it hits to blue.

RY item (Green) puts an enemy into a state of superposition that skews towards collapsing into red: 87.5% chance of switching to red to be precise.

The classical X gate (Blue) will simply flip the qubit 100% of the time, turning all enemies it hits into the opposite colour.

Build towers to defend your portal! The cost of each tower is displayed on the right.

2021-07-24 15:45 UTC, bharathcs commented on game/src/environment/Fog/Black.shader
> +uniform vec4 color = vec4(0, 0, 0, 1);
Never mind I realised you did color everywhere

2021-07-24 15:46 UTC, bharathcs commented on game/src/ui/gameplay/Prompts/AnimatedSprite.gd
>  ]
grammar, rephrased cuz you're not allowing enemies anything, you and your vs u and ur, rewriting items to be easier to understand, spaces and punctuation

2021-07-24 15:47 UTC, bharathcs commented on game/project.godot
> +"class": "prompt",
Fixed in f802cd13

2021-07-25 15:03 UTC, bharathcs commented on game/src/Scope/GoldScoping.gd
> +	+ "Thats all for now. Have Fun!"
fun

2021-07-25 15:03 UTC, bharathcs commented on game/src/Scope/QuantumButton.gd
> +	+ "Click here to swap between colour"
colours

2021-07-25 15:03 UTC, bharathcs commented on game/src/Scope/QuantumButton.gd
> +	+ "Click here\n to swap between color" \
tc fixed.

2021-07-25 15:03 UTC, bharathcs commented on game/src/Scope/ItemScoping.gd
> +	+ "and equip an item by dragging and dropping"
tc fixed

2021-07-25 15:04 UTC, bharathcs commented on game/src/Scope/HealthBarScopeLabel.gd
> +	+ "If any reaches zero, GAMEOVER"
tc fixed.

2021-07-25 15:04 UTC, bharathcs commented on game/src/Scope/TowerButtonScopes.gd
> +	+ "Alternatively you can press Q on your keyboard"
tc fixed.

2021-07-25 15:04 UTC, bharathcs commented on game/src/environment/Fog/Black.shader
> +uniform vec4 color = vec4(0, 0, 0, 1);
tc ignored.

2021-07-25 15:08 UTC, bharathcs requested changes
and i also see an empty file GoldCost.gd

2021-07-25 15:29 UTC, bharathcs approved these changes

2021-07-25 15:32 UTC, merged